producto:
  property: Producto Profile Prod

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/db_producto?useSSL=false&serverTimezone=UTC
